name: Go CI

on:
  push:
    branches: [ master, main ]
    paths-ignore:
      - '**/test/**'
      - '**/doc/**'
  pull_request:
    branches: [ master, main ]
    paths-ignore:
      - '**/test/**'
      - '**/doc/**'

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'checker-go/go.mod'
          cache: true

      - name: Install Dependencies
        run: |
          cd checker-go
          go mod download

      - name: Run Tests
        run: |
          cd checker-go
          go test -v ./...

